cabal-version:      3.0
name:               frontend-wasm
version:            0.1.0.0
build-type:         Simple

executable frontend-wasm-exe
  main-is:          Main.hs
  other-modules:
    NGOWidgets
  build-depends:
    base >=4.14 && <5,
    common,
    reflex-dom,
    aeson,
    text
  hs-source-dirs:   .
  default-language: Haskell2010
  default-extensions:
    OverloadedStrings
    RecordWildCards
